### ISSUE TITLE
Duplicate step numbering. Documentation error in 'Getting started' section on gh-pages

### ISSUE THREAD

**Issue by Neobyte01** [Norditech-AB/STELLA#32]
A minor issue. The ordered list of steps in the 'Getting started' docs contains duplicate for **4**.

Link:
https://docs.stellaframework.com/Getting_Started.html#step-4-setup-the-environment

Screenshot:
<img width="561" alt="image" src="https://github.com/Norditech-AB/STELLA/assets/31895118/308f465c-ba5b-465e-bd28-389ec1ba0b2b">

**Comment by philip-alm** [comment]
Thanks for the issue! Fixed.
